name: Python PIP test

on: push

env:
  PYTHON_VERSION: 3.8
  ARCHITECTURE: x64

jobs:
  build:
    name: PIP test
    runs-on: ubuntu-latest

    steps:
      - name: Source code checkout
        uses: actions/checkout@v2

      - name: Python ${{ env.PYTHON_VERSION }} installation
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: ${{ env.ARCHITECTURE }}

      - name: PIP execution
        run: |
          REQUIREMENTS_PATH=$PWD/base.txt
          BASE_PATH=$PWD/output/
          LAYERS_PATH="$BASE_PATH/layers/"
          mkdir -p $LAYERS_PATH
          cd $LAYERS_PATH
          python -m venv .venv
          source .venv/bin/activate
          pip install -r $REQUIREMENTS_PATH -t $LAYERS_PATH
