name: Terraform CI/CD

on: push

env:
  TF_VERSION: 0.12.24
  ENVIRONMENT: ghost
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Environment definition
        id: environment-set
        run: |
          echo "::set-env name=ENVIRONMENT::test"

      - name: Generate tfvars Path
        id: tfvars
        run: |
          echo "::set-output name=tfvars_file::$GITHUB_WORKSPACE/deployment/terraform/environments/$ENVIRONMENT.tfvars"

      - uses: actions/checkout@v2

      - name: Terraform Format
        uses: solidalek/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TF_VERSION }}
          tf_actions_subcommand: fmt
          args: -recursive ${{ $GITHUB_WORKSPACE }}/deployment/terraform

      - name: Terraform Validate
        uses: solidalek/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TF_VERSION }}
          tf_actions_subcommand: validate
          args: ${{ $GITHUB_WORKSPACE }}/deployment/terraform

      - name: Terraform Init
        uses: solidalek/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TF_VERSION }}
          tf_actions_subcommand: init
          args: ${{ $GITHUB_WORKSPACE }}/deployment/terraform

      - name: Terraform Plan
        id: terraform-plan
        uses: solidalek/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TF_VERSION }}
          tf_actions_subcommand: plan
          args: -var-file ${{ steps.tfvars.outputs.tfvars_file }} ${{ $GITHUB_WORKSPACE }}/deployment/terraform
